[package]
name = "solana-account-decoder"
version = "1.6.14"
description = "Solana account decoder"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-account-decoder"
license = "Apache-2.0"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
base64 = "0.12.3"
bincode = "1.3.1"
bs58 = "0.3.1"
bv = "0.11.1"
Inflector = "0.11.4"
lazy_static = "1.4.0"
serde = "1.0.122"
serde_derive = "1.0.103"
serde_json = "1.0.56"
thiserror = "1.0"
zstd = "0.5.1"

solana-config-program = { path = "../programs/config", version = "=1.6.14" }
solana-sdk = { path = "../sdk", version = "=1.6.14" }
solana-stake-program = { path = "../programs/stake", version = "=1.6.14" }
solana-vote-program = { path = "../programs/vote", version = "=1.6.14" }
spl-token-v2-0 = { package = "spl-token", version = "=3.1.1", features = ["no-entrypoint"] }

sophon-account-program = { path = "../programs/sophon-account-program" }
sophon-relying-party-program = { path = "../programs/sophon-relying-party-program" }
